root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/netscribe ./cmd/netscribe"
  bin = "./tmp/netscribe"
  args_bin = ["serve", "--config", "netscribe.yaml"]
  include_ext = ["go", "yaml", "sql"]
  exclude_dir = ["tmp", "web", "testdata", "deploy"]
  exclude_regex = ["_test\\.go$"]
  delay = 300
  stop_on_error = true
  send_interrupt = true
  kill_delay = "2s"

[log]
  time = false

[misc]
  clean_on_exit = true
