// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (at, user_id, username, action, entity, entity_id, result, ip, detail)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditParams struct {
	At       string
	UserID   sql.NullInt64
	Username string
	Action   string
	Entity   string
	EntityID string
	Result   string
	Ip       string
	Detail   string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.At,
		arg.UserID,
		arg.Username,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Result,
		arg.Ip,
		arg.Detail,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, user_id, username, "action", entity, entity_id, result, ip, detail FROM audit_log
WHERE (?1 = 0 OR id < ?1)
  AND (?2 = '' OR action = ?2)
  AND (?3 = '' OR username = ?3)
ORDER BY id DESC
LIMIT ?4
`

type ListAuditParams struct {
	BeforeID interface{}
	Action   interface{}
	Username interface{}
	MaxRows  int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit,
		arg.BeforeID,
		arg.Action,
		arg.Username,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Result,
			&i.Ip,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAudit = `-- name: PruneAudit :exec
DELETE FROM audit_log WHERE at < ?
`

func (q *Queries) PruneAudit(ctx context.Context, at string) error {
	_, err := q.db.ExecContext(ctx, pruneAudit, at)
	return err
}
