// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
)

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, mac, ip, hostname, vendor, kind, description, source, online, first_seen_at, last_seen_at, x, y FROM devices WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.Ip,
		&i.Hostname,
		&i.Vendor,
		&i.Kind,
		&i.Description,
		&i.Source,
		&i.Online,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getDeviceByIP = `-- name: GetDeviceByIP :one
SELECT id, mac, ip, hostname, vendor, kind, description, source, online, first_seen_at, last_seen_at, x, y FROM devices WHERE ip = ? ORDER BY online DESC, last_seen_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetDeviceByIP(ctx context.Context, ip string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByIP, ip)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.Ip,
		&i.Hostname,
		&i.Vendor,
		&i.Kind,
		&i.Description,
		&i.Source,
		&i.Online,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getDeviceByIPWithoutMAC = `-- name: GetDeviceByIPWithoutMAC :one
SELECT id, mac, ip, hostname, vendor, kind, description, source, online, first_seen_at, last_seen_at, x, y FROM devices WHERE mac = '' AND ip = ?
`

func (q *Queries) GetDeviceByIPWithoutMAC(ctx context.Context, ip string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByIPWithoutMAC, ip)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.Ip,
		&i.Hostname,
		&i.Vendor,
		&i.Kind,
		&i.Description,
		&i.Source,
		&i.Online,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getDeviceByMAC = `-- name: GetDeviceByMAC :one
SELECT id, mac, ip, hostname, vendor, kind, description, source, online, first_seen_at, last_seen_at, x, y FROM devices WHERE mac = ?
`

func (q *Queries) GetDeviceByMAC(ctx context.Context, mac string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByMAC, mac)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Mac,
		&i.Ip,
		&i.Hostname,
		&i.Vendor,
		&i.Kind,
		&i.Description,
		&i.Source,
		&i.Online,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (mac, ip, hostname, vendor, kind, description, source, online, first_seen_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
RETURNING id
`

type InsertDeviceParams struct {
	Mac         string
	Ip          string
	Hostname    string
	Vendor      string
	Kind        string
	Description string
	Source      string
	FirstSeenAt string
	LastSeenAt  string
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDevice,
		arg.Mac,
		arg.Ip,
		arg.Hostname,
		arg.Vendor,
		arg.Kind,
		arg.Description,
		arg.Source,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, mac, ip, hostname, vendor, kind, description, source, online, first_seen_at, last_seen_at, x, y FROM devices
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Mac,
			&i.Ip,
			&i.Hostname,
			&i.Vendor,
			&i.Kind,
			&i.Description,
			&i.Source,
			&i.Online,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnlineDeviceAddrs = `-- name: ListOnlineDeviceAddrs :many
SELECT id, ip FROM devices WHERE online = 1
`

type ListOnlineDeviceAddrsRow struct {
	ID int64
	Ip string
}

func (q *Queries) ListOnlineDeviceAddrs(ctx context.Context) ([]ListOnlineDeviceAddrsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOnlineDeviceAddrs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOnlineDeviceAddrsRow
	for rows.Next() {
		var i ListOnlineDeviceAddrsRow
		if err := rows.Scan(&i.ID, &i.Ip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceOffline = `-- name: SetDeviceOffline :exec
UPDATE devices SET online = 0 WHERE id = ?
`

func (q *Queries) SetDeviceOffline(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setDeviceOffline, id)
	return err
}

const updateDeviceFromScan = `-- name: UpdateDeviceFromScan :exec
UPDATE devices
SET mac = ?, ip = ?, hostname = ?, vendor = ?, kind = ?, description = ?, online = 1, last_seen_at = ?
WHERE id = ?
`

type UpdateDeviceFromScanParams struct {
	Mac         string
	Ip          string
	Hostname    string
	Vendor      string
	Kind        string
	Description string
	LastSeenAt  string
	ID          int64
}

func (q *Queries) UpdateDeviceFromScan(ctx context.Context, arg UpdateDeviceFromScanParams) error {
	_, err := q.db.ExecContext(ctx, updateDeviceFromScan,
		arg.Mac,
		arg.Ip,
		arg.Hostname,
		arg.Vendor,
		arg.Kind,
		arg.Description,
		arg.LastSeenAt,
		arg.ID,
	)
	return err
}
