// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Device struct {
	ID          int64
	Mac         string
	Ip          string
	Hostname    string
	Vendor      string
	Kind        string
	Description string
	Source      string
	Online      int64
	FirstSeenAt string
	LastSeenAt  string
	X           sql.NullFloat64
	Y           sql.NullFloat64
}

type Scan struct {
	ID             int64
	Target         string
	Status         string
	StartedAt      string
	FinishedAt     sql.NullString
	Error          string
	DeviceCount    int64
	LinkCount      int64
	ContainerCount int64
}
