// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scans.sql

package db

import (
	"context"
	"database/sql"
)

const finishScan = `-- name: FinishScan :execrows
UPDATE scans SET status = ?, finished_at = ?, error = ? WHERE id = ? AND status = 'running'
`

type FinishScanParams struct {
	Status     string
	FinishedAt sql.NullString
	Error      string
	ID         int64
}

func (q *Queries) FinishScan(ctx context.Context, arg FinishScanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishScan,
		arg.Status,
		arg.FinishedAt,
		arg.Error,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getScan = `-- name: GetScan :one
SELECT id, target, status, started_at, finished_at, error, device_count, link_count, container_count FROM scans WHERE id = ?
`

func (q *Queries) GetScan(ctx context.Context, id int64) (Scan, error) {
	row := q.db.QueryRowContext(ctx, getScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.DeviceCount,
		&i.LinkCount,
		&i.ContainerCount,
	)
	return i, err
}

const insertScan = `-- name: InsertScan :one
INSERT INTO scans (target, status, started_at) VALUES (?, 'running', ?) RETURNING id, target, status, started_at, finished_at, error, device_count, link_count, container_count
`

type InsertScanParams struct {
	Target    string
	StartedAt string
}

func (q *Queries) InsertScan(ctx context.Context, arg InsertScanParams) (Scan, error) {
	row := q.db.QueryRowContext(ctx, insertScan, arg.Target, arg.StartedAt)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.DeviceCount,
		&i.LinkCount,
		&i.ContainerCount,
	)
	return i, err
}

const listScans = `-- name: ListScans :many
SELECT id, target, status, started_at, finished_at, error, device_count, link_count, container_count FROM scans ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListScans(ctx context.Context, limit int64) ([]Scan, error) {
	rows, err := q.db.QueryContext(ctx, listScans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.Target,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.DeviceCount,
			&i.LinkCount,
			&i.ContainerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScanCounts = `-- name: SetScanCounts :exec
UPDATE scans SET device_count = ?, link_count = ?, container_count = ? WHERE id = ?
`

type SetScanCountsParams struct {
	DeviceCount    int64
	LinkCount      int64
	ContainerCount int64
	ID             int64
}

func (q *Queries) SetScanCounts(ctx context.Context, arg SetScanCountsParams) error {
	_, err := q.db.ExecContext(ctx, setScanCounts,
		arg.DeviceCount,
		arg.LinkCount,
		arg.ContainerCount,
		arg.ID,
	)
	return err
}
