// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, idHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id_hash, user_id, csrf_token, created_at, last_seen_at, expires_at, ip, user_agent FROM sessions WHERE id_hash = ?
`

func (q *Queries) GetSession(ctx context.Context, idHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id_hash, user_id, csrf_token, created_at, last_seen_at, expires_at, ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	IDHash     string
	UserID     int64
	CsrfToken  string
	CreatedAt  string
	LastSeenAt string
	ExpiresAt  string
	Ip         string
	UserAgent  string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.IDHash,
		arg.UserID,
		arg.CsrfToken,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const pruneSessions = `-- name: PruneSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) PruneSessions(ctx context.Context, expiresAt string) error {
	_, err := q.db.ExecContext(ctx, pruneSessions, expiresAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE id_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt string
	IDHash     string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.IDHash)
	return err
}

const trimUserSessions = `-- name: TrimUserSessions :exec
DELETE FROM sessions
WHERE sessions.user_id = ?1
  AND sessions.id_hash NOT IN (
    SELECT newest.id_hash FROM sessions AS newest
    WHERE newest.user_id = ?1
    ORDER BY newest.created_at DESC, newest.rowid DESC
    LIMIT ?2
  )
`

type TrimUserSessionsParams struct {
	OwnerID int64
	Keep    int64
}

func (q *Queries) TrimUserSessions(ctx context.Context, arg TrimUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, trimUserSessions, arg.OwnerID, arg.Keep)
	return err
}
