// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const countEnabledAdmins = `-- name: CountEnabledAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND disabled = 0
`

func (q *Queries) CountEnabledAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, role, disabled, must_change_password, failed_logins, locked_until, created_at, last_login_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, username, display_name, password_hash, role, disabled, must_change_password, failed_logins, locked_until, created_at, last_login_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, display_name, password_hash, role, disabled, must_change_password, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, display_name, password_hash, role, disabled, must_change_password, failed_logins, locked_until, created_at, last_login_at
`

type InsertUserParams struct {
	Username           string
	DisplayName        string
	PasswordHash       string
	Role               string
	Disabled           int64
	MustChangePassword int64
	CreatedAt          string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Disabled,
		arg.MustChangePassword,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.MustChangePassword,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, password_hash, role, disabled, must_change_password, failed_logins, locked_until, created_at, last_login_at FROM users ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.Disabled,
			&i.MustChangePassword,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE users SET failed_logins = ?, locked_until = ? WHERE id = ?
`

type RecordLoginFailureParams struct {
	FailedLogins int64
	LockedUntil  sql.NullString
	ID           int64
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordLoginFailure, arg.FailedLogins, arg.LockedUntil, arg.ID)
	return err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users SET failed_logins = 0, locked_until = NULL, last_login_at = ? WHERE id = ?
`

type RecordLoginSuccessParams struct {
	LastLoginAt sql.NullString
	ID          int64
}

func (q *Queries) RecordLoginSuccess(ctx context.Context, arg RecordLoginSuccessParams) error {
	_, err := q.db.ExecContext(ctx, recordLoginSuccess, arg.LastLoginAt, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users
SET password_hash = ?, must_change_password = ?, failed_logins = 0, locked_until = NULL
WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash       string
	MustChangePassword int64
	ID                 int64
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.MustChangePassword, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserRoleAndDisabled = `-- name: SetUserRoleAndDisabled :exec
UPDATE users SET role = ?, disabled = ? WHERE id = ?
`

type SetUserRoleAndDisabledParams struct {
	Role     string
	Disabled int64
	ID       int64
}

func (q *Queries) SetUserRoleAndDisabled(ctx context.Context, arg SetUserRoleAndDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setUserRoleAndDisabled, arg.Role, arg.Disabled, arg.ID)
	return err
}
